/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package App._EventHandling.InSpring;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
